### ISSUE TITLE
Actividad 2 infografía 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-2-infografia-MarleneRamirez0731#1]
Marlene Maricela Osorio Ramírez 1° BS 
Actividad 2: infografía

![png_20220901_171036_0000](https://user-images.githubusercontent.com/112357070/188021739-26410a9e-8274-47dc-bcc7-c5458b7e4350.png)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by gilbertovelasco1** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
